# Generated by Django 4.0 on 2022-08-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='creditcarddetails',
            options={'verbose_name_plural': 'Credit Card Details'},
        ),
        migrations.AlterField(
            model_name='creditcarddetails',
            name='credit_card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
