# Generated by Django 3.2 on 2022-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220814_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='cart.Cart_Item'),
        ),
    ]
