# Generated by Django 3.2 on 2022-08-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
